version: '3'
services:
  student-reg-service:
    image: studentregservice
    container_name: studentregservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345Wq
    ports:
      - 5432:5432